### ISSUE TITLE
Gonerino crashes youtube when sideloaded

### ISSUE THREAD

**Issue by binnichtaktiv** [castdrian/Gonerino#10]
If you inject Gonerino.dylib into sideloaded youtube it sometimes crashes youtube. i have tested with and without Gonerino and without it, it works without problems so it must be a bug of Gonerino. It crashes for example when you go to the settings symbol in the video player

https://github.com/user-attachments/assets/9dcca50e-3c0e-4e58-aed4-626d43ba4da9

**Comment by castdrian** [comment]
I'm in a 3 day SAP Workshop so I won't be able to debug until roughly seven hours from now, it'd be great If you could collect any console logs/exceptions/crash dumps that happen and just dump em here in the issue, I'll investigate later 🥲

**Comment by binnichtaktiv** [comment]
> I'm in a 3 day SAP Workshop so I won't be able to debug until roughly seven hours from now, it'd be great If you could collect any console logs/exceptions/crash dumps that happen and just dump em here in the issue, I'll investigate later 🥲

You mean a .ips logfile? Or can I get something better? Im not jailbroken

**Comment by castdrian** [comment]
If you launch the Console app on your Mac you can stream your devices NSLogs, also you could try to test different versions of the tweak using LiveContainer to narrow it down, ips logs are also probably useful

**Comment by binnichtaktiv** [comment]
> If you launch the Console app on your Mac you can stream your devices NSLogs, also you could try to test different versions of the tweak using LiveContainer to narrow it down, ips logs are also probably useful

I dont have a mac anymore :( I could send you the ipa so that you can try. [iPA](https://gofile.io/d/gGl9pf) - try to do what I did in the video and yt should crash.

[ips log](https://gofile.io/d/ONNVpg)

**Comment by castdrian** [comment]
okay yep, thanks for that, found the issue

**Comment by castdrian** [comment]
fixed in 0.4.3

**Comment by binnichtaktiv** [comment]
> fixed in 0.4.3

thanks. Just wondering did you find anything useful in the ips file I send?

**Comment by castdrian** [comment]
> > fixed in 0.4.3
> 
> 
> 
> thanks. Just wondering did you find anything useful in the ips file I send?

Yes lol, threw it at Claude sonnet and it was trying to meddle with sheets it doesn't have any reason to meddle with
